packageExtensions:
  '@atls/config-jest@*':
    dependencies:
      jest: '28'
      typescript: '4.6.4'
  '@atls/webpack-proto-imports-loader@*':
    dependencies:
      webpack: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20230929.hash-7d0fd35a.cjs

enableGlobalCache: false
