compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  '@atls/config-jest@*':
    dependencies:
      jest: 28
      typescript: 4.6.4
  '@atls/webpack-proto-imports-loader@*':
    dependencies:
      webpack: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
