compressionLevel: mixed

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@atls/config-jest@*':
    dependencies:
      jest: '28'
      typescript: '4.6.4'
  '@atls/webpack-proto-imports-loader@*':
    dependencies:
      webpack: '*'

yarnPath: .yarn/releases/yarn-remote.cjs

defaultSemverRangePrefix: ''

preferReuse: true

pnpEnableEsmLoader: true
