name: Publish to registry

on:
  pull_request
  # workflow_dispatch:
  # pull_request:
    # types:
    #   - closed
    # branches:
    #   - master
    # paths-ignore:
    #   - '.github/**'

jobs:
  publish:
    # if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: atls/shared/.github/workflows/publish.yaml@master
    # uses: atls/shared/.github/workflows/publish.yaml@feat/force-npm
    permissions: write-all
    with:
      appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
    secrets:
      appPrivateKey: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
      npmAuthToken: ${{ secrets.NPM_TOKEN }}
